### ISSUE TITLE
Crash with GnuRadio 3.7.12

### ISSUE THREAD

**Issue by ghulands** [csete/gqrx#634]
When I run gqrx with SoapySDR's UHD driver, I get a crash with the following backtrace.

```
Thread 1 "gqrx" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff3392e97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff3394801 in __GI_abort () at abort.c:79
#2  0x00007ffff33dd897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff350ab9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff33e490a in malloc_printerr (str=str@entry=0x7ffff350c890 "double free or corruption (!prev)") at malloc.c:5350
#4  0x00007ffff33ebe84 in _int_free (have_lock=0, p=0x555555b8c190, av=0x7ffff373fc40 <main_arena>) at malloc.c:4281
#5  0x00007ffff33ebe84 in __GI___libc_free (mem=0x555555b8c1a0) at malloc.c:3124
#6  0x00007ffff70f3c2b in gr::flowgraph::~flowgraph() () at /usr/local/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#7  0x00007ffff70fbe45 in boost::detail::sp_counted_impl_p<gr::flowgraph>::dispose() () at /usr/local/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#8  0x00007ffff70b766a in boost::detail::sp_counted_base::release() () at /usr/local/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#9  0x00007ffff7100559 in gr::hier_block2_detail::~hier_block2_detail() () at /usr/local/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#10 0x00007ffff70fee98 in gr::hier_block2::~hier_block2() () at /usr/local/lib/libgnuradio-runtime-3.7.12.0.so.0.0.0
#11 0x00007ffff5c06413 in virtual thunk to source_impl::~source_impl() () at /usr/local/lib/libgnuradio-osmosdr.so.0.1.5git
#12 0x0000555555609dba in boost::detail::sp_counted_base::release() ()
#13 0x000055555561f2c6 in receiver::set_input_device(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#14 0x0000555555616f0d in MainWindow::loadConfig(QString, bool, bool) ()
#15 0x0000555555619d77 in MainWindow::MainWindow(QString, bool, QWidget*) ()
#16 0x00005555555bb2c6 in main ()
```
Any ideas?

**Comment by csete** [comment]
Looks like a problem with SoapySDR and UHD integration. Nothing to fix in gqrx. For discussions and tech support please use the mailing list, http://gqrx.dk/user-support
